### PR TITLE
Refactor getnoise

### PR DESCRIPTION
**Pull request by AlecThomson**
Hey @AstroRipples, this should be a fix for #22. It's also a fairly large refactor. Would you be happy to test?

### CODE REVIEW

**Comment by AstroRipples** [comment]
Hey Alec. Thanks for pushing these commits. Happy to test when you're ready for me to do so. I made a new virtualenv for testing and installed RACS-tools via `pip3 install git+https://github.com/AlecThomson/RACS-tools`, but I get the same issue as before so I suppose the changes are still migrating to the pip server?

**Comment by AlecThomson** [comment]
Thanks @AstroRipples ! Ah you'll need to do:
```bash
pip3 install git+https://github.com/AlecThomson/RACS-tools@noisefix
```
to get the PR branch

**Comment by AstroRipples** [comment]
Hey Alec. Okay, updated my local install. Unfortunately I hit a `bus error`:

```
(RACStools)$ getnoise_list --file bad_channels_chan512.txt RMSynth_chan512/qcube.fits RMSynth_chan512/ucube.fits
Flagging iteration 1 of 1
Errore di bus
```

**Comment by AlecThomson** [comment]
Ouch ok - I think a bus error is local hardware problem. But to sanity check (since I've been pushing a few updates) want to try un/reinstalling and retrying?

**Comment by AstroRipples** [comment]
Sure... Hmm this time I get errors when trying to install RACS-tools 😆 just to be sure we're on the same page, I'm running the following steps:
```
virtualenv -p python3.9 RACStools
source RACStools/bin/activate
pip3 install -U pip setuptools wheel
pip3 install numpy
pip3 install gcc7
pip3 install git+https://github.com/AlecThomson/RACS-tools@noisefix
```

And during the final pip3 install I get errors -- I've copied the output to this log (which is just a text file): 
[install_err.log](https://github.com/AlecThomson/RACS-tools/files/10173560/install_err.log)

**Comment by AlecThomson** [comment]
Oh dear!

I've never seen gcc through pip, but I'm not sure that'd do what you want. I also usually use `conda`, rather than venvs :/ 

Perhaps try installing gcc and gfortran via your usual package manager (`brew`, `macports`, `apt-get`, `pacman`, etc) and see if that helps?

**Comment by AlecThomson** [comment]
@AstroRipples - I'm going to go ahead and merge these changes. These fixes seem to work well on the data I've tested so far. Feel free to DM me on any install issues - or even consider using the containerised version if you like.

**Comment by AstroRipples** [comment]
Hey Alec. No worries. I've been running further tests and I get the same error regardless of whether I use `pip3 install gcc7`. For what it's worth I've also set up a lot of other software on our compute nodes using the same recipe of:
```
virtualenv -p python ${VENV_NAME}
source ${VENV_NAME}/bin/activate
pip3 install -U pip setuptools wheel
pip3 install numpy
pip3 install gcc7
pip3 install ${other dependencies}
pip3 install ${package}
```

and this is the first time I've encountered problems of this sort. It seems to be a problem with how RACS-tools is interacting with a virtualenv, so it would be good to get this issue figured out.

I looked into this a little further and ran two other experiments outside of a virtualenv (just installing RACS-tools directly on our nodes).

1. Installing RACS-tools via `pip3 install RACS-tools --user` :
    This ran the channel checking but then fell over with the same `UnitConversionError` that I mentioned in issue #22 : 
``` 
...
[106] Checking channel 440
[106] Checking channel 441
[106] Checking channel 442
[106] Time taken was 46.81034941901453s
Traceback (most recent call last):
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/quantity.py", line 890, in to_value
    scale = self.unit._to(unit)
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/core.py", line 1093, in _to
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'Unit("Jy / beam")' is not a scaled version of 'Unit(dimensionless)'
...
```

2. Installing RACS-tools via `pip3 install git+https://github.com/AlecThomson/RACS-tools --user`:
    Exact same outcome as within the virtualenv, the wheel fails to build:
```
... 
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for RACS-tools
  Running setup.py clean for RACS-tools
Failed to build RACS-tools
Installing collected packages: RACS-tools
  Attempting uninstall: RACS-tools
    Found existing installation: RACS-tools 2.1.0
    Uninstalling RACS-tools-2.1.0:
      Successfully uninstalled RACS-tools-2.1.0
  Running setup.py install for RACS-tools ... error
  error: subprocess-exited-with-error
...
```

**Comment by AlecThomson** [comment]
Hi Chris,

I'm not gonna lie - I'm really confused by the `pip install gcc` - this _shouldn't_ be a thing that you pip install XD (but I could be wrong)

`pip install gcc7` points to this repo - https://github.com/bh107/python-gcc which seems to be both old, and just appears to make some python bindings for gcc. Again, I would recommend installing `gcc` using your standard package manager or `conda`.
EDIT: Looking at the repo a little more - it has a random version of gcc7 (now old) tarred in the repo. I'm standing with my statement above though haha

You'll need `gcc` and/or `gfortran` available in compiled form somewhere - can you `which gcc` and/or `which gfortran`? We have `fortran` code in this repo which needs a compiler.

The repeated error (with the units) is probably because it pulled the older RACS-Tools. v2.1.1 should have the fix in place. The newer version will fix all this.

**Comment by AstroRipples** [comment]
Heh, yeah it's been pretty standard to `pip3 install gcc` in our virtualenvs 😉 

In any case... both `gcc` and `gfortran` are available in the virtualenv by default anyway:
```
(RACStools) riseley@lofar8:~$ which gcc
/usr/bin/gcc
(RACStools) riseley@lofar8:~$ which gfortran
/usr/bin/gfortran
```

In terms of versioning:
```
(RACStools) riseley@lofar8:~$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(RACStools) riseley@lofar8:~$ gfortran --version
GNU Fortran (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Even outside of a virtualenv, when I load up gcc: 

```
riseley@lofar8:~$ gcc-setup
[irainit] 'gcc' version '12.1.0' is now ready on 
```

I encounter the same error when trying to `pip3 install git+https://github.com/AlecThomson/RACS-tools`. So the compilers are there, but the wheel fails to build whether I'm inside or outside a virtualenv 🤷

**Comment by AlecThomson** [comment]
I think these issues are related to your local installs of `python` and `gcc`. My usual recommendation is to use `conda` for a fresh install and control of install location. Otherwise, I think this is an issue for your sysadmins, I'm afraid.

Just to make sure I'm not going crazy, I did a fresh install of Python and successfully installed using both a `conda` env and a `virtualenv`. See results here:
https://gist.github.com/AlecThomson/a9008f7b0c20b89ab6d59bc752bdd895 

Sorry I can't really be of more help :/

**Comment by AstroRipples** [comment]
Yeah `conda` isn't available, and when I try to install it the build wheel fails to build `pycosat`. We don't have root access and the one sysadmin is only a sysadmin part-time. I guess this is where we leave it then, I'll try something else or resort to looking at the channels manually 🤷

**Comment by AlecThomson** [comment]
Hey @AstroRipples - having slept on it here are some options which might help

1. If you have write access to the filesystems you should be able to install miniconda (definitely my recommended path) and install from there
```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
```
2. If you have singularity (or Docker), you can use the container image:
```bash
singularity pull docker://alecthomson/racstools:2.1.1
```
3. Since this script doesn't use the fortran part, you could pull the repo and a) manually install the requirements and run the script, or b) modify the `setup.py` to skip over the fortran bits. This is probably the most janky option

Hopefully one of these will work out for you!

**Comment by AstroRipples** [comment]
Hey Alec 👋 

Thanks for the additional recipes... I followed the recommended path and I've now got `Miniconda3` installed and operational and I've been able to complete the Conda install instructions on the main `RACS-tools` page 🥳 

In further news, `getnoise_list` also now works successfully on my MeerKAT cubes 🎉 

Perhaps not the optimal place for this, so let me know if that's the case, but when I run with the default clip level, `getnoise_list` suggests about 1//3 of my channels are "bad". Do you have an example configuration that you've found successful for SPICE-RACS or POSSUM?

**Pull request merged**
